WITH TOTAL AS (
    SELECT S.HACKER_ID, S.CHALLENGE_ID, MAX(S.SCORE) AS TOT
    FROM SUBMISSIONS S
    GROUP BY S.HACKER_ID, S.CHALLENGE_ID
)

SELECT H.HACKER_ID, H.NAME, SUM(T.TOT) AS TOTAL_SCORE
FROM HACKERS H
JOIN TOTAL T ON H.HACKER_ID = T.HACKER_ID 
GROUP BY H.HACKER_ID, H.NAME
HAVING SUM(T.TOT)<>0
ORDER BY TOTAL_SCORE DESC, H.HACKER_ID;
